### ISSUE TITLE
Update readme to contain project information

### ISSUE THREAD

**Issue by zach-gilbert** [zach-gilbert/zach-react-app#3]
### Task list for the readme:
- [x] What the project is
- [x] How the project works
- [x] Purpose for the project
- [x] Reformat instructions to build and run the project
